version: "3"
services:
  firefox:
    image: firefox:latest
    build: ./firefox
    container_name: firefox-lab
    tmpfs: /dev/shm
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
